---
title: "Happiness Project"
output: html_document
---

```{r}

Happiness <- read.delim("~/STAT101AData/Happiness.txt", header = TRUE)
attach(Happiness)

Happiness$Household[Household==9]= NA
Happiness$Age[Age==98|Age==99]= NA
Happiness$Children[Children==9]= NA
Happiness$OwnHome[OwnHome == 9] = NA
Happiness$OwnHome[OwnHome == 0] = 8
Happiness$Health[ Health == 9] = NA
Happiness$Health[ Health == 0] = 8
Happiness$Instagram[Instagram == 9] = NA
Happiness$Instagram[Instagram == 0] = 8
Happiness$Marital[Marital == 9] = NA
Happiness$Education[Education == 97 | Education == 98 | Education == 99] = NA
Happiness$JobSat[JobSat == 8 | JobSat == 9] = NA
Happiness$Income[ Income ==999998 | Income == 999999] = NA
Happiness$WorkHrs[WorkHrs==999] =  NA
Happiness$WorkHrs[WorkHrs==(-1)] =  998
Happiness$Happy[Happy == 0 | Happy == 8 | Happy == 9 ] = NA

m1 <- lm(Happy ~ Household + Health + Age + Children + OwnHome + Instagram + Marital + Sex + Education + JobSat + Income + WorkHrs, na.action = na.exclude)
summary(m1)

library(car)
library(alr3)

Happiness$Children[Children == 0] =  0.01
Happiness$Income[Income == 0] = 0.01
Happiness$JobSat[JobSat == 0] = 0.01
Happiness$Education[Education == 0] = 0.01
Happiness$WorkHrs[WorkHrs == 0] = 0.01

Happiness
attach(Happiness)

pm1 <- powerTransform(cbind(Happy,WorkHrs,Health,OwnHome,Household,Age,Children,Marital,Sex,Education,JobSat,Income,Instagram)~1)
summary(pm1)

```




```{r}

tHappy <- (Happy^(0.733))
tWorkHrs <- WorkHrs^(1.45)
tHealth <- Health^(0.195)
tOwnHome <- OwnHome^(-0.187)
tHousehold <- Household^(-0.324)
tAge <- Age^(0.465)
tChildren <- Children^(0.333)
tMarital <- Marital^(0.09)
tSex <- Sex^(1.035)
tEducation <- Education^(1.206)
tJobSat <- JobSat^(-0.443)
tIncome <- Income^(0.044)
tInstagram <- Instagram^(0.394)


m2 <- lm(tHappy ~ tHousehold + tHealth + tAge + tChildren + tOwnHome + tInstagram + tMarital + tSex + tEducation + tJobSat + tIncome + tWorkHrs, na.action = na.exclude)
summary(m2)

pairs(tHappy ~ tHousehold + tHealth + tAge + tChildren + tOwnHome + tInstagram + tMarital + tSex + tEducation + tJobSat + tIncome + tWorkHrs)

par(mfrow=c(2,2))
avPlot(m2,variable=tHealth)
avPlot(m2,variable=tOwnHome)
avPlot(m2,variable=tHousehold)
avPlot(m2,variable=tAge)
avPlot(m2,variable=tChildren)
avPlot(m2,variable=tInstagram)
avPlot(m2,variable=tMarital)
avPlot(m2,variable=tSex)
avPlot(m2,variable=tEducation)
avPlot(m2,variable=tJobSat)
avPlot(m2,variable=tIncome)
avPlot(m2,variable=tWorkHrs)

StanRes2 <- rstandard(m2)
par(mfrow=c(2,2))

plot(tHousehold,StanRes2, ylab="Standardized Residuals")
plot(tHealth,StanRes2, ylab="Standardized Residuals")
plot(tOwnHome,StanRes2, ylab="Standardized Residuals")
plot(tInstagram,StanRes2, ylab="Standardized Residuals")
plot(tMarital,StanRes2, ylab="Standardized Residuals")
plot(tSex,StanRes2, ylab="Standardized Residuals")
plot(tAge,StanRes2, ylab="Standardized Residuals")
plot(tChildren,StanRes2, ylab="Standardized Residuals")
plot(tEducation,StanRes2, ylab="Standardized Residuals")
plot(tJobSat,StanRes2, ylab="Standardized Residuals")
plot(tIncome,StanRes2, ylab="Standardized Residuals")
plot(tWorkHrs,StanRes2, ylab="Standardized Residuals")


```

```{r}
X <-cbind(tHappy,tWorkHrs,tHealth,tOwnHome,tHousehold,tAge,tChildren,tMarital,tSex,tEducation,tJobSat,tIncome,tInstagram)
vif(m2)
library(leaps)
newX <- na.exclude(X)

newX2 <- newX[,2:13]
b <- regsubsets(as.matrix(newX2),newX[,1], nvmax = 12)
rs <- summary(b)
rs$adjr2
rs
par(mfrow=c(1,1))
plot(1:12,rs$adjr2,xlab="Subset Size",ylab="Adjusted R-squared")

om1 <- lm(tHappy ~ tMarital)
om2 <- lm(tHappy ~ tMarital + tIncome)
om3 <- lm(tHappy ~ tMarital + tHealth + tOwnHome)
om4 <- lm(tHappy ~ tMarital + tHealth + tOwnHome + tJobSat)
om5 <- lm(tHappy ~ tMarital + tHealth + tOwnHome + tJobSat + tChildren)
om6 <- lm(tHappy ~ tMarital + tHealth + tOwnHome + tJobSat + tChildren + tHousehold)
om7 <- lm(tHappy ~ tMarital + tHealth + tOwnHome + tJobSat + tChildren + tHousehold + tIncome)
om8 <- lm(tHappy ~ tMarital + tHealth + tOwnHome + tJobSat + tChildren + tHousehold + tIncome + tEducation)
om9 <- lm(tHappy ~ tMarital + tHealth + tOwnHome + tJobSat + tChildren + tHousehold + tIncome + tEducation + tWorkHrs)
om10 <- lm(tHappy ~ tMarital + tHealth + tOwnHome + tJobSat + tChildren + tHousehold + tIncome + tEducation + tWorkHrs + tSex)
om11 <- lm(tHappy ~ tMarital + tHealth + tOwnHome + tJobSat + tChildren + tHousehold + tIncome + tEducation + tWorkHrs + tSex + tInstagram)
om12 <- m2

Rad <- rs$adjr2

#Subset size=1
n <- length(om1$residuals); p <- 1
#Calculate AIC
AIC1 <- extractAIC(om1,k=2)[2]
#Calculate AICc = AIC + 2k(k+1)/(n-k-1)
AICc1 <- extractAIC(om1,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC1 <-extractAIC(om1,k=log(n))[2]

#Subset size=2
p <-2
#Calculate AIC
AIC2 <- extractAIC(om2,k=2)[2]
#Calculate AICc
AICc2 <- extractAIC(om2,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC2 <- extractAIC(om2,k=log(n))[2]

#Subset size=3
p <- 3
#Calculate AIC
AIC3 <- extractAIC(om3,k=2)[2]
#Calculate AICc
AICc3 <- extractAIC(om3,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC3 <- extractAIC(om3,k=log(n))[2]

#Subset size=4
p <- 4
#Calculate AIC
AIC4 <- extractAIC(om4,k=2)[2]
#Calculate AICc
AICc4 <- extractAIC(om4,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC4 <- extractAIC(om4,k=log(n))[2]

#Subset size=5
p <- 5
#Calculate AIC
AIC5 <- extractAIC(om5,k=2)[2]
#Calculate AICc
AICc5 <- extractAIC(om5,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC5 <- extractAIC(om5,k=log(n))[2]

#Subset size=6
p <- 6
#Calculate AIC
AIC6 <- extractAIC(om6,k=2)[2]
#Calculate AICc = AIC + 2k(k+1)/(n-k-1)
AICc6 <- extractAIC(om6,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC6 <-extractAIC(om6,k=log(n))[2]

#Subset size=7
p <-7
#Calculate AIC
AIC7 <- extractAIC(om7,k=2)[2]
#Calculate AICc
AICc7 <- extractAIC(om7,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC7 <- extractAIC(om7,k=log(n))[2]

#Subset size=8
p <- 8
#Calculate AIC
AIC8 <- extractAIC(om8,k=2)[2]
#Calculate AICc
AICc8 <- extractAIC(om8,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC8 <- extractAIC(om8,k=log(n))[2]

#Subset size=9
p <- 9
#Calculate AIC
AIC9 <- extractAIC(om9,k=2)[2]
#Calculate AICc
AICc9 <- extractAIC(om9,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC9 <- extractAIC(om9,k=log(n))[2]

#Subset size=10
p <- 10
#Calculate AIC
AIC10 <- extractAIC(om10,k=2)[2]
#Calculate AICc
AICc10 <- extractAIC(om10,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC10 <- extractAIC(om10,k=log(n))[2]

#Subset size=11
p <- 11
#Calculate AIC
AIC11 <- extractAIC(om11,k=2)[2]
#Calculate AICc = AIC + 2k(k+1)/(n-k-1)
AICc11 <- extractAIC(om11,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC11 <-extractAIC(om11,k=log(n))[2]

#Subset size=12
p <-12
#Calculate AIC
AIC12 <- extractAIC(om12,k=2)[2]
#Calculate AICc
AICc12 <- extractAIC(om12,k=2)[2]+2*(p+2)*(p+3)/(n-p-1)
#Calculate BIC
BIC12 <- extractAIC(om12,k=log(n))[2]

AIC <- c(AIC1,AIC2,AIC3,AIC4,AIC5,AIC6,AIC7,AIC8,AIC9,AIC10,AIC11,AIC12)
AICc <- c(AICc1,AICc2,AICc3,AICc4,AICc5,AICc6,AICc7,AICc8,AICc9,AICc10,AICc11,AICc12)
BIC <- c(BIC1,BIC2,BIC3,BIC4,BIC5,BIC6,BIC7,BIC8,BIC9,BIC10,BIC11,BIC12)

table <- data.frame(Size=1:12, Radj2=Rad,AIC=AIC, AICc=AICc, BIC=BIC)
table

```
For R^2, subset size 11 is best, 
For AIC, subset size 7 is best, 
FOr AICc, subset size 7 is best,
For BIC, subset size 4 is bset

```{r}
summary(om4)
summary(om7)
summary(om8)
summary(om11)
```



```{r}
library(leaps)
HappinessSub = Happiness[complete.cases(Happiness), ]  #New Dataset without NAs
HappinessSub
dim(HappinessSub)
om1 = lm(I(Happy^(0.7328))~I(Health^(0.1951)), data=HappinessSub)
n = length(om1$residuals)

m3 = lm(I(Happy^0.7328)~I(Health^0.1951)+I(OwnHome^-0.1871)+I(Household^-0.3244)+I(Age^0.4648)+I(Children^0.3336)+I(Instagram^0.3944)+I(Marital^0.0918)+I(Sex^1.0353)+I(Education^1.2063)+I(JobSat^-0.4434)+I(Income^0.0439)+I(WorkHrs^1.452),data = HappinessSub, na.action=na.exclude)

backAIC <- step(m3,direction="backward", data=HappinessSub)
backBIC <- step(m3,direction="backward", data=HappinessSub, k=log(n))

mint <- lm((Happy^(0.7328))~1,data=HappinessSub)
forwardAIC <- step(mint,scope=list(lower=~1, 
                                   upper=~I(Health^0.1951)+I(OwnHome^-0.1871)+I(Household^-0.3244)+I(Age^0.4648)+I(Children^0.3336)+I(Instagram^0.3944)+I(Marital^0.0918)+I(Sex^1.0353)+I(Education^1.2063)+I(JobSat^-0.4434)+I(Income^0.0439)+I(WorkHrs^1.452)),
                   direction="forward", data=HappinessSub)

forwardBIC <- step(mint,scope=list(lower=~1,                          upper=~I(Health^0.1951)+I(OwnHome^-0.1871)+I(Household^-0.3244)+I(Age^0.4648)+I(Children^0.3336)+I(Instagram^0.3944)+I(Marital^0.0918)+I(Sex^1.0353)+I(Education^1.2063)+I(JobSat^-0.4434)+I(Income^0.0439)+I(WorkHrs^1.452)),
                   direction="forward", data=HappinessSub,k=log(n))


BestSubset = lm(tHappy ~ tHealth + tOwnHome + tHousehold + 
  tChildren + tMarital + 
  tJobSat + tIncome, na.action = na.exclude)
summary(BestSubset)
plot(BestSubset)


StanRes3 <- rstandard(BestSubset)
par(mfrow=c(1,1))
plot(tHealth,StanRes3, ylab="Standardized Residuals")
plot(tOwnHome,StanRes3, ylab="Standardized Residuals")
plot(tHousehold,StanRes3, ylab="Standardized Residuals")
plot(tChildren,StanRes3, ylab="Standardized Residuals")
plot(tMarital,StanRes3, ylab="Standardized Residuals")
plot(tJobSat,StanRes3, ylab="Standardized Residuals")
plot(tIncome,StanRes3, ylab="Standardized Residuals")


```
